# Generated by Django 3.0.2 on 2020-01-13 16:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100, verbose_name='Cliente')),
                ('codigo', models.IntegerField(max_length=9, verbose_name='Código')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='TOTAL')),
                ('anulado', models.BooleanField()),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Colaborador')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='LineaDeServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio unitario')),
                ('descuento', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento (%)')),
                ('nuevoPrecio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nuevo precio')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripcion')),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.Servicio')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Venta')),
            ],
            options={
                'verbose_name': 'Linea de servicio',
                'verbose_name_plural': 'Lineas de servicio',
            },
        ),
        migrations.CreateModel(
            name='LineaDeProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('descuento', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento (%)')),
                ('nuevoPrecio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nuevo precio')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Subtotal')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Venta')),
            ],
            options={
                'verbose_name': 'Linea de producto',
                'verbose_name_plural': 'Lineas de producto',
            },
        ),
    ]
