# Generated by Django 3.0.2 on 2020-01-20 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='colaborador',
        ),
        migrations.AddField(
            model_name='lineadeproducto',
            name='colaborador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.Colaborador'),
            preserve_default=False,
        ),
    ]
