# Generated by Django 3.0.2 on 2020-01-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_auto_20200120_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='codigo',
            field=models.IntegerField(verbose_name='Código'),
        ),
    ]
