# Generated by Django 3.0.2 on 2020-01-21 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('venta', '0004_auto_20200120_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineadeproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto'),
        ),
        migrations.AlterField(
            model_name='lineadeservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Servicio'),
        ),
    ]
