# Generated by Django 3.0.2 on 2020-01-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_auto_20200120_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineadeservicio',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
    ]
