# Generated by Django 3.0.2 on 2020-01-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_auto_20200121_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('N', 'No guardada'), ('G', 'Guardada')], default=None, max_length=2),
        ),
    ]
