# Generated by Django 3.0.2 on 2020-01-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0007_venta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineadeproducto',
            name='nuevoPrecio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nuevo precio'),
        ),
    ]
