# Generated by Django 3.0.2 on 2020-01-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0008_auto_20200126_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineadeproducto',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal'),
        ),
    ]
