# Generated by Django 3.0.2 on 2020-02-10 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('venta', '0010_auto_20200206_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineadeproducto',
            name='colaborador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='usuario.Colaborador'),
            preserve_default=False,
        ),
    ]
