# Generated by Django 3.0.2 on 2020-02-10 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0011_lineadeproducto_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='email',
            field=models.CharField(default=1, max_length=50, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='venta',
            name='telefono',
            field=models.IntegerField(default=1, verbose_name='Teléfono'),
            preserve_default=False,
        ),
    ]
