# Generated by Django 3.0.2 on 2020-02-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0012_auto_20200210_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineadeproducto',
            name='nuevoPrecio',
        ),
        migrations.AddField(
            model_name='lineadeproducto',
            name='nuevoSubtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Nuevo subtotal'),
            preserve_default=False,
        ),
    ]
